# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastLm <- function(yr, Xr) {
    .Call('_ZCAPM_fastLm', PACKAGE = 'ZCAPM', yr, Xr)
}

EM_loop <- function(beta_hat, Z_hat, sigma_sq_hat, p_hat, port_exc_ret, mkt_exc_ret, mkt_sigma, tol, MaxIter, criterion, start_timestamp, end_timestamp) {
    .Call('_ZCAPM_EM_loop', PACKAGE = 'ZCAPM', beta_hat, Z_hat, sigma_sq_hat, p_hat, port_exc_ret, mkt_exc_ret, mkt_sigma, tol, MaxIter, criterion, start_timestamp, end_timestamp)
}

